@Red55.Uma.Authz.Proxy_HostAddress = http://authz.house
@CLIENT_ID=gitlab
@CLIENT_SECRET=TfrJeVtGN1BYjCVygGIIGzIfN3gsCx1Q
@UNAME=lkorokh
@PASSWORD=qQ123456

POST {{Red55.Uma.Authz.Proxy_HostAddress}}/realms/test/protocol/openid-connect/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded

client_id={{CLIENT_ID}}&client_secret={{CLIENT_SECRET}}&username={{UNAME}}&password={{PASSWORD}}&grant_type=password&scope=email%20profile

